# Generated by Django 5.1.1 on 2024-10-22 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managedata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casecategory',
            fields=[
                ('categoryid', models.TextField(blank=True, db_column='CategoryId', primary_key=True, serialize=False)),
                ('categoryname', models.TextField(blank=True, db_column='CategoryName', null=True)),
            ],
            options={
                'db_table': 'caseCategory',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('formid', models.TextField(blank=True, db_column='FormID', primary_key=True, serialize=False)),
                ('content1', models.IntegerField(blank=True, db_column='Content1', null=True)),
                ('content2', models.IntegerField(blank=True, db_column='Content2', null=True)),
                ('content3', models.IntegerField(blank=True, db_column='Content3', null=True)),
                ('content4', models.IntegerField(blank=True, db_column='Content4', null=True)),
                ('content5', models.IntegerField(blank=True, db_column='Content5', null=True)),
                ('content6', models.IntegerField(blank=True, db_column='Content6', null=True)),
                ('content7', models.IntegerField(blank=True, db_column='Content7', null=True)),
                ('content8', models.IntegerField(blank=True, db_column='Content8', null=True)),
                ('content9', models.IntegerField(blank=True, db_column='Content9', null=True)),
                ('content10', models.TextField(blank=True, db_column='Content10', null=True)),
                ('responded', models.BooleanField(default=False)),
                ('studentid', models.ForeignKey(blank=True, db_column='StudentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managedata.students')),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Studentcases',
            fields=[
                ('caseid', models.TextField(blank=True, db_column='CaseID', primary_key=True, serialize=False)),
                ('categoryid', models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managestudents.casecategory')),
                ('courseid', models.ForeignKey(blank=True, db_column='CourseId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managedata.courses')),
                ('employeeid', models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('formid', models.ForeignKey(blank=True, db_column='FormID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managestudents.forms')),
                ('studentid', models.ForeignKey(blank=True, db_column='StudentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managedata.students')),
            ],
            options={
                'db_table': 'studentCases',
            },
        ),
    ]
