# Generated by Django 5.1.1 on 2024-10-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forms',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='forms',
            name='content10',
        ),
        migrations.AddField(
            model_name='forms',
            name='checkbox_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
