# Generated by Django 5.1.1 on 2024-11-06 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0002_alter_forms_options_remove_forms_content10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forms',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
