# Generated by Django 5.1.1 on 2024-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0003_forms_created_at_forms_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='flagged_course',
            field=models.CharField(blank=True, db_column='flagged_course', max_length=15, null=True),
        ),
    ]
