# Generated by Django 5.1.1 on 2024-11-03 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0003_forms_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
