# Generated by Django 5.1.1 on 2024-11-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0004_forms_flagged_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
