# Generated by Django 5.1.1 on 2024-11-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0004_forms_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='created_at',
        ),
    ]
