# Generated by Django 5.1.1 on 2024-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0005_forms_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='intervention_form_checkbox',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='intervention_form_issues',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
