# Generated by Django 5.1.1 on 2024-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0006_forms_intervention_form_checkbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='formid',
            field=models.UUIDField(blank=True, db_column='FormID', primary_key=True, serialize=False),
        ),
    ]
