# Generated by Django 5.1.1 on 2024-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0006_forms_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
