# Generated by Django 5.1.1 on 2024-11-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managestudents', '0007_alter_forms_formid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='responded',
            field=models.IntegerField(default=0),
        ),
    ]
