# Generated by Django 5.1.1 on 2024-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.TextField(blank=True, db_column='CourseID', primary_key=True, serialize=False)),
                ('catalogueno', models.TextField(blank=True, db_column='CatalogueNo', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('classdescription', models.TextField(blank=True, db_column='ClassDescription', null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.TextField(blank=True, db_column='Trimester', null=True)),
                ('flagstatus', models.IntegerField(blank=True, db_column='FlagStatus', null=True)),
                ('journal1', models.IntegerField(blank=True, db_column='Journal1', null=True)),
                ('journal2', models.IntegerField(blank=True, db_column='Journal2', null=True)),
                ('assessment1', models.IntegerField(blank=True, db_column='Assessment1', null=True)),
                ('assessment2', models.IntegerField(blank=True, db_column='Assessment2', null=True)),
                ('assessment3', models.IntegerField(blank=True, db_column='Assessment3', null=True)),
                ('currentscore', models.IntegerField(blank=True, db_column='CurrentScore', null=True)),
                ('finalgrade', models.IntegerField(blank=True, db_column='FinalGrade', null=True)),
            ],
            options={
                'db_table': 'studentGrades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.TextField(blank=True, db_column='StudentID', primary_key=True, serialize=False)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('acadprogdesc', models.TextField(blank=True, db_column='AcadProgDesc', null=True)),
                ('phoneno', models.TextField(blank=True, db_column='PhoneNo', null=True)),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
