# Generated by Django 5.1.1 on 2024-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('form_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=255)),
                ('content1', models.IntegerField()),
                ('content2', models.IntegerField()),
                ('content3', models.IntegerField()),
                ('content4', models.IntegerField()),
                ('content5', models.IntegerField()),
                ('content6', models.IntegerField()),
                ('content7', models.IntegerField()),
                ('content8', models.IntegerField()),
                ('content9', models.IntegerField()),
                ('content10', models.IntegerField()),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
    ]
