# Generated by Django 5.1.1 on 2024-10-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedata', '0002_formresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='student_id',
        ),
        migrations.AddField(
            model_name='formresponse',
            name='studentid',
            field=models.ForeignKey(blank=True, db_column='StudentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managedata.students'),
        ),
    ]
